# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      # ignore all boto3 patch updates
      - dependency-name: "boto3"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
